name: 'Terraform Deploy'

on:
  workflow_dispatch:
    inputs:
      location:
        type: string
        required: true
        default: 'westeurope'
        description: 'Azure Region'
      client_ip:
        type: string
        required: true
        default: '94.134.104.164'
        description: 'Client IP'
      initial:
        type: string
        required: true
        default: 'false'
        description: 'Initial Deployment (true or false)'

jobs:
  terraform_deploy_shared:
    name: Terraform Deploy Shared
    uses: gutt02/terraform-azure-infrastructure-as-code/.github/workflows/terraform_deploy_shared.yml
    with:
      location: github.event.inputs.location
      client_ip: github.event.inputs.client_ip
      initial: github.event.inputs.initial

  # terraform_deploy_windows_virtual_machine:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}